# Generated by Django 3.2.6 on 2023-09-15 08:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Formmodel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nama_form", models.CharField(max_length=100)),
                ("no_form", models.CharField(max_length=51)),
                ("category_form", models.CharField(max_length=100)),
                ("file_upload", models.FileField(upload_to="uploads/")),
            ],
        ),
        migrations.CreateModel(
            name="FormProsedurm",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nama_prosedur", models.CharField(max_length=100)),
                ("category_prosedur", models.CharField(blank=True, max_length=100)),
                ("file_upload_prosedur", models.FileField(upload_to="uploads/")),
                ("no_prosedur", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("ip_address", models.GenericIPAddressField()),
            ],
        ),
    ]
