# Generated by Django 3.2.6 on 2023-09-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formprosedurm",
            name="category_prosedur",
            field=models.CharField(max_length=100),
        ),
    ]
