# Generated by Django 3.2.6 on 2023-10-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_auto_20230915_1547"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryKegiatanm",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="uploads/")),
                ("date_added", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
