# Generated by Django 3.2.6 on 2023-10-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_gallerykegiatanm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallerykegiatanm",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
