# Generated by Django 3.2.6 on 2023-10-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_alter_gallerykegiatanm_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendence",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("bulan", models.CharField(max_length=15)),
                ("jumlah", models.IntegerField(max_length=5)),
                ("bestat1", models.IntegerField(max_length=5)),
                ("bestat1bag", models.CharField(max_length=40)),
                ("bestat2", models.IntegerField(max_length=5)),
                ("bestat2bag", models.CharField(max_length=40)),
                ("badat1", models.IntegerField(max_length=5)),
                ("bedat1bag", models.CharField(max_length=40)),
                ("badat2", models.IntegerField(max_length=5)),
                ("bedat2bag", models.CharField(max_length=40)),
            ],
        ),
    ]
