# Generated by Django 3.2.6 on 2023-10-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_attendence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendence",
            name="badat1",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="attendence",
            name="badat2",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="attendence",
            name="bestat1",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="attendence",
            name="bestat2",
            field=models.IntegerField(null=True),
        ),
    ]
