# Generated by Django 3.2.6 on 2023-10-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_auto_20231009_1424"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendence",
            name="jumlah",
            field=models.IntegerField(null=True),
        ),
    ]
