# Generated by Django 3.2.6 on 2023-10-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_alter_attendence_jumlah"),
    ]

    operations = [
        migrations.CreateModel(
            name="Indekskehadiran",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bulan", models.CharField(max_length=10)),
                ("kehadiranbulan", models.IntegerField()),
                ("bestsection1", models.CharField(max_length=25)),
                ("bestsection1kehadiran", models.IntegerField()),
                ("bestsection2", models.CharField(max_length=25)),
                ("bestsection2kehadiran", models.IntegerField()),
                ("worstsection1", models.CharField(max_length=25)),
                ("worstsection1kehadiran", models.IntegerField()),
                ("worstsection2", models.CharField(max_length=25)),
                ("worstsection2kehadiran", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="Attendence",
        ),
    ]
