# Generated by Django 3.2.6 on 2023-10-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_auto_20231009_1605"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataPoint",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("value", models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name="Indekskehadiran",
        ),
    ]
