# Generated by Django 3.2.6 on 2023-10-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_auto_20231011_1135"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datapoint",
            name="date",
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name="datapoint",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
