# Generated by Django 3.2.6 on 2023-10-12 03:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0011_auto_20231012_0919"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DataPoint",
        ),
    ]
