# Generated by Django 3.2.6 on 2023-10-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0014_alter_gallerykegiatanm_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallerykegiatanm",
            name="image",
            field=models.ImageField(upload_to="uploads/"),
        ),
    ]
