# Generated by Django 3.2.6 on 2023-10-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0015_alter_gallerykegiatanm_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="JadwalBusM",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("titikStart", models.CharField(max_length=30)),
                ("plant", models.CharField(max_length=2)),
                ("via", models.CharField(max_length=20)),
                ("seat", models.IntegerField(max_length=2)),
                ("shift1", models.CharField(max_length=5, null=True)),
                ("shift2", models.CharField(max_length=5, null=True)),
                ("shift3", models.CharField(max_length=5, null=True)),
            ],
        ),
    ]
