# Generated by Django 3.2.6 on 2023-10-23 03:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0016_jadwalbusm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jadwalbusm",
            name="seat",
            field=models.IntegerField(),
        ),
    ]
