# Generated by Django 3.2.6 on 2023-10-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0017_alter_jadwalbusm_seat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitor",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
