# Generated by Django 3.2.6 on 2023-10-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0018_alter_visitor_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="menuKantinM",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nama_file", models.CharField(max_length=35)),
                ("file", models.FileField(upload_to="uploads/manukantin")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
