# Generated by Django 3.2.6 on 2023-10-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0019_menukantinm"),
    ]

    operations = [
        migrations.AddField(
            model_name="jadwalbusm",
            name="nobus",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
