# Generated by Django 3.2.6 on 2023-11-06 07:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0020_jadwalbusm_nobus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jadwalbusm",
            name="nobus",
        ),
    ]
