# Generated by Django 3.2.6 on 2023-11-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0021_remove_jadwalbusm_nobus"),
    ]

    operations = [
        migrations.CreateModel(
            name="PengumumanYpmiM",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nama_pengumuman", models.CharField(blank=True, max_length=35)),
                ("tanggal_upload", models.DateTimeField()),
                ("file_pengumuman", models.FileField(upload_to="uploads/pengumuman")),
            ],
        ),
    ]
