# Generated by Django 3.2.6 on 2023-11-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0022_pengumumanypmim"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pengumumanypmim",
            name="tanggal_upload",
            field=models.DateField(),
        ),
    ]
