# Generated by Django 3.2.6 on 2023-11-07 04:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0023_alter_pengumumanypmim_tanggal_upload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallerykegiatanm",
            name="image",
            field=models.ImageField(upload_to="uploads/kegiatan"),
        ),
        migrations.AlterField(
            model_name="menukantinm",
            name="file",
            field=models.FileField(upload_to="uploads/menuKantin"),
        ),
    ]
