# Generated by Django 3.2.6 on 2023-11-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0024_auto_20231107_1122"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pengumumanypmim",
            name="file_pengumuman",
            field=models.FileField(upload_to="uploads/"),
        ),
    ]
