# Generated by Django 3.2.6 on 2023-11-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0025_alter_pengumumanypmim_file_pengumuman"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pengumumanypmim",
            name="nama_pengumuman",
            field=models.CharField(max_length=35),
        ),
    ]
