# Generated by Django 3.2.6 on 2023-11-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0026_alter_pengumumanypmim_nama_pengumuman"),
    ]

    operations = [
        migrations.AddField(
            model_name="pengumumanypmim",
            name="no_pengumuman",
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name="pengumumanypmim",
            name="file_pengumuman",
            field=models.FileField(upload_to="uploads/pengumuman"),
        ),
    ]
