# Generated by Django 3.2.6 on 2023-11-07 08:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0028_auto_20231107_1450"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prosedurm",
            name="no_prosedur",
        ),
    ]
