# Generated by Django 3.2.6 on 2023-11-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0029_remove_prosedurm_no_prosedur"),
    ]

    operations = [
        migrations.RenameField(
            model_name="datapoint",
            old_name="id",
            new_name="id_dataPoint",
        ),
        migrations.RenameField(
            model_name="formmodel",
            old_name="id",
            new_name="id_form",
        ),
        migrations.RenameField(
            model_name="gallerykegiatanm",
            old_name="id",
            new_name="id_gallery",
        ),
        migrations.RenameField(
            model_name="jadwalbusm",
            old_name="id",
            new_name="id_jadwalBus",
        ),
        migrations.RenameField(
            model_name="menukantinm",
            old_name="id",
            new_name="id_menuKantin",
        ),
        migrations.RenameField(
            model_name="pengumumanypmim",
            old_name="id",
            new_name="id_pengumuman",
        ),
        migrations.RenameField(
            model_name="prosedurm",
            old_name="id",
            new_name="id_prosedur",
        ),
        migrations.RenameField(
            model_name="visitor",
            old_name="id",
            new_name="id_visitor",
        ),
        migrations.AlterField(
            model_name="pengumumanypmim",
            name="file_pengumuman",
            field=models.FileField(upload_to="uploads/"),
        ),
    ]
