# Generated by Django 3.2.6 on 2023-11-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0030_auto_20231108_1341"),
    ]

    operations = [
        migrations.RenameField(
            model_name="datapoint",
            old_name="id_dataPoint",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="formmodel",
            old_name="id_form",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="gallerykegiatanm",
            old_name="id_gallery",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="jadwalbusm",
            old_name="id_jadwalBus",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="menukantinm",
            old_name="id_menuKantin",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="pengumumanypmim",
            old_name="id_pengumuman",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="prosedurm",
            old_name="id_prosedur",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="visitor",
            old_name="id_visitor",
            new_name="id",
        ),
        migrations.AlterField(
            model_name="pengumumanypmim",
            name="file_pengumuman",
            field=models.FileField(upload_to="uploads/pengumuman/"),
        ),
    ]
