# Generated by Django 3.2.6 on 2023-11-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0031_auto_20231108_1342"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prosedurm",
            name="file_upload",
            field=models.FileField(upload_to="uploads/prosedur"),
        ),
    ]
