# Generated by Django 3.2.6 on 2023-11-14 03:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0032_alter_prosedurm_file_upload"),
    ]

    operations = [
        migrations.RenameField(
            model_name="datapoint",
            old_name="date",
            new_name="bulan",
        ),
        migrations.AddField(
            model_name="datapoint",
            name="divisi",
            field=models.CharField(default="divisions", max_length=25),
        ),
    ]
