# Generated by Django 3.2.6 on 2023-11-14 04:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0033_auto_20231114_1038"),
    ]

    operations = [
        migrations.RenameField(
            model_name="datapoint",
            old_name="value",
            new_name="indexs",
        ),
    ]
