# Generated by Django 3.2.6 on 2023-11-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0035_auto_20231114_1341"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("no_pengumuman", models.CharField(max_length=255)),
                ("nama_pengumuman", models.CharField(max_length=255)),
                ("tanggal_upload", models.DateField()),
                ("file_pengumuman", models.FileField(upload_to="uploads/pengumuman")),
            ],
        ),
        migrations.DeleteModel(
            name="PengumumanYpmiM",
        ),
    ]
