# Generated by Django 3.2.6 on 2023-11-16 02:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0037_alter_announcement_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="announcement",
            name="no_pengumuman",
        ),
    ]
