# Generated by Django 3.2.6 on 2023-11-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0038_remove_announcement_no_pengumuman"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="catThn",
            field=models.CharField(default="", max_length=4),
        ),
    ]
