# Generated by Django 3.2.6 on 2023-11-16 04:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0039_announcement_catthn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="nama_pengumuman",
            field=models.TextField(max_length=255),
        ),
    ]
