# Generated by Django 3.2.6 on 2023-11-16 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0040_alter_announcement_nama_pengumuman"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="catThn",
            field=models.CharField(default="2023", max_length=4),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="nama_pengumuman",
            field=models.CharField(max_length=255),
        ),
    ]
