# Generated by Django 3.2.6 on 2023-11-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0041_auto_20231116_1134"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="catThn",
            field=models.CharField(max_length=4),
        ),
    ]
