# Generated by Django 3.2.6 on 2023-11-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0042_alter_announcement_catthn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="catThn",
            field=models.CharField(max_length=5),
        ),
    ]
