# Generated by Django 3.2.6 on 2023-11-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0043_alter_announcement_catthn"),
    ]

    operations = [
        migrations.AddField(
            model_name="datapoint",
            name="terendahLabel",
            field=models.CharField(default="", max_length=35),
        ),
        migrations.AddField(
            model_name="datapoint",
            name="terendahValue",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="datapoint",
            name="tertinggiLabel",
            field=models.CharField(default="", max_length=35),
        ),
        migrations.AddField(
            model_name="datapoint",
            name="tertinggiValue",
            field=models.FloatField(default=0),
        ),
    ]
