# Generated by Django 3.2.6 on 2023-11-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0044_auto_20231117_1026"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataKehadiran",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("Bulan", models.CharField(max_length=255)),
                ("divisi", models.CharField(max_length=45)),
                ("image", models.ImageField(upload_to="images/")),
                ("tanggal", models.DateField()),
                ("keterangan", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="DataPoint",
        ),
    ]
