# Generated by Django 3.2.6 on 2023-11-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0045_auto_20231118_0747"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datakehadiran",
            name="image",
            field=models.ImageField(upload_to="images/kehadiran/"),
        ),
    ]
