# Generated by Django 3.2.6 on 2023-11-18 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0046_alter_datakehadiran_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jadwalbusm",
            name="via",
            field=models.CharField(max_length=55),
        ),
    ]
