# Generated by Django 3.2.6 on 2023-11-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0048_aturan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jadwalbusm",
            name="via",
            field=models.TextField(max_length=255),
        ),
    ]
