# Generated by Django 3.2.6 on 2023-11-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0049_alter_jadwalbusm_via"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datakehadiran",
            name="image",
            field=models.FileField(upload_to="images/kehadiran/"),
        ),
    ]
