# Generated by Django 3.2.6 on 2023-11-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0050_alter_datakehadiran_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datakehadiran",
            name="image",
            field=models.ImageField(upload_to="images/kehadiran/"),
        ),
    ]
