# Generated by Django 3.2.6 on 2023-11-22 08:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0051_alter_datakehadiran_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GalleryKegiatanm",
        ),
    ]
