# Generated by Django 3.2.6 on 2023-11-22 09:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0052_delete_gallerykegiatanm"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prosedurm",
            old_name="file_upload",
            new_name="file_upload_prosedur",
        ),
    ]
