# Generated by Django 3.2.6 on 2023-11-22 09:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0053_rename_file_upload_prosedurm_file_upload_prosedur"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prosedurm",
            old_name="file_upload_prosedur",
            new_name="file_upload",
        ),
    ]
