# Generated by Django 4.2.7 on 2023-11-28 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0054_rename_file_upload_prosedur_prosedurm_file_upload"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchPage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "announcement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.announcement",
                    ),
                ),
                (
                    "aturan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.aturan"
                    ),
                ),
                (
                    "datakehadiran",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.datakehadiran",
                    ),
                ),
                (
                    "formmodel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.formmodel",
                    ),
                ),
                (
                    "jadwalbusm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.jadwalbusm",
                    ),
                ),
                (
                    "menukantinm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.menukantinm",
                    ),
                ),
                (
                    "prosedurm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.prosedurm",
                    ),
                ),
                (
                    "visitor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.visitor",
                    ),
                ),
            ],
        ),
    ]
