# Generated by Django 4.2.7 on 2023-11-29 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_searchpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchPage',
        ),
    ]
