# Generated by Django 4.2.7 on 2023-12-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0057_activeuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pengumuman",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nama_pengumuman", models.CharField(max_length=100)),
                ("tahun", models.CharField(max_length=5)),
                ("file_pengumuman", models.FileField(upload_to="uploads/pengumuman")),
                ("tanggal_upload", models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name="Announcement",
        ),
    ]
