# Generated by Django 4.2.7 on 2023-12-08 04:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0058_pengumuman_delete_announcement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pengumuman",
            name="nama_pengumuman",
            field=models.CharField(max_length=355),
        ),
    ]
