# Generated by Django 4.2.7 on 2024-02-05 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0059_alter_pengumuman_nama_pengumuman"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingApproval",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("training_date", models.DateField()),
                ("participants", models.TextField()),
                ("supervisor_approval", models.BooleanField(default=False)),
                ("hrd_approval", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
