# Generated by Django 4.2.7 on 2024-02-06 02:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0060_trainingapproval"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trainingapproval",
            old_name="supervisor_approval",
            new_name="manager_approval",
        ),
    ]
