# Generated by Django 4.2.7 on 2024-02-06 06:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0061_rename_supervisor_approval_trainingapproval_manager_approval"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TrainingApproval",
        ),
    ]
