# Generated by Django 4.2.7 on 2024-02-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0063_trainingapproval"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingapproval",
            name="trainer",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
