# Generated by Django 4.2.7 on 2024-03-26 02:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0064_trainingapproval_trainer"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TrainingApproval",
        ),
    ]
