# Generated by Django 4.2.7 on 2024-03-26 03:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0065_delete_trainingapproval"),
    ]

    operations = [
        migrations.CreateModel(
            name="trainingSchedule",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("judulTraining", models.CharField(max_length=55, null=True)),
                ("planPeserta1", models.IntegerField(null=True)),
                ("planPeserta2", models.IntegerField(null=True)),
                ("planPeserta3", models.IntegerField(null=True)),
                ("durasiJam", models.CharField(max_length=4)),
                ("durasiHari", models.CharField(max_length=4)),
                ("pesertaOP", models.CharField(max_length=1, null=True)),
                ("pesertaLDR", models.CharField(max_length=1, null=True)),
                ("pesertaFR", models.CharField(max_length=1, null=True)),
                ("pesertaGF", models.CharField(max_length=1, null=True)),
                ("pesertaSPV", models.CharField(max_length=1, null=True)),
                ("pesertaSTAFF", models.CharField(max_length=1, null=True)),
                ("pesertaMNG", models.CharField(max_length=1, null=True)),
            ],
        ),
    ]
