# Generated by Django 4.2.7 on 2024-03-26 03:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0066_trainingschedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingschedule",
            name="actPeserta1",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="trainingschedule",
            name="actPeserta2",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="trainingschedule",
            name="actPeserta3",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="trainingschedule",
            name="actPeserta4",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="trainingschedule",
            name="planPeserta4",
            field=models.IntegerField(null=True),
        ),
    ]
