# Generated by Django 4.2.7 on 2024-03-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0067_trainingschedule_actpeserta1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingschedule",
            name="actPeserta1",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trainingschedule",
            name="actPeserta2",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trainingschedule",
            name="actPeserta3",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trainingschedule",
            name="actPeserta4",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trainingschedule",
            name="durasiHari",
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name="trainingschedule",
            name="durasiJam",
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name="trainingschedule",
            name="judulTraining",
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AlterField(
            model_name="trainingschedule",
            name="pesertaFR",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name="trainingschedule",
            name="pesertaGF",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name="trainingschedule",
            name="pesertaLDR",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name="trainingschedule",
            name="pesertaMNG",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name="trainingschedule",
            name="pesertaOP",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name="trainingschedule",
            name="pesertaSPV",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name="trainingschedule",
            name="pesertaSTAFF",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name="trainingschedule",
            name="planPeserta1",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trainingschedule",
            name="planPeserta2",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trainingschedule",
            name="planPeserta3",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trainingschedule",
            name="planPeserta4",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
