# Generated by Django 4.2.7 on 2024-03-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0068_alter_trainingschedule_actpeserta1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingschedule",
            name="trainingCat",
            field=models.CharField(blank=True, max_length=55),
        ),
    ]
