# Generated by Django 4.2.7 on 2024-04-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0069_trainingschedule_trainingcat"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingschedule",
            name="bulan",
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
