# Generated by Django 4.2.7 on 2024-04-03 03:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0070_trainingschedule_bulan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainingschedule",
            name="bulan",
        ),
    ]
