# Generated by Django 4.2.7 on 2024-04-04 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0072_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("location", models.CharField(max_length=100)),
                ("participants", models.TextField()),
                ("trainer", models.CharField(max_length=100)),
                ("approved_by_occupation_manager", models.BooleanField(default=False)),
                ("approved_by_general_manager", models.BooleanField(default=False)),
                ("approved_by_hrd_manager", models.BooleanField(default=False)),
                ("background", models.TextField()),
                ("target_after", models.TextField()),
                ("occupation", models.CharField(max_length=100)),
                (
                    "general_manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="general_manager",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manager",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="DataKehadiran",
        ),
    ]
