# Generated by Django 4.2.7 on 2024-04-04 04:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_remove_userprofile_full_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
